### ISSUE TITLE
Inno Setup v5/v5 issue re {cf}

### ISSUE THREAD

**Issue by brownrb** [ASCOMInitiative/ASCOMPlatform#20]
The ASCOM script generator uses {cf} to generate directory paths for INNO. But {cf} is invalid in v6 of INNO. Should I be using {commoncf} instead?

**Comment by Peter-Simpson** [comment]
Hi Robert,

{cf} does work in Inno 6, it is translated quietly, under the hood, to {commoncf} by the compiler. The compiler output should have lines looking like these:
`
Warning: Constant "cf" has been renamed. Use "commoncf" instead or consider using its "auto" form.
Warning: Constant "pf" has been renamed. Use "commonpf" instead or consider using its "auto" `

Personally I am going to change all my {cf} and [pf] references to the new format because the original versions may stop being supported by the Inno team at some point. Unfortunately I can't change these in our template file because they need to work on both Inno 5 and Inno 6 and only the original {cf} and {pf} constants work in both.

I'm closing this issue because it doesn't require a Platform change
